### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by chentengming** [isaacaflores2/GarageDoor#1]
![image](https://user-images.githubusercontent.com/10330569/61259700-e5514480-a7ad-11e9-8d1d-d7337c81c91f.png)

**Comment by isaacaflores2** [comment]
Hey sorry you had an issue with the install. It has been real busy at work and I'm going on a trip this weekend, so I'll get back to you in two weeks.

**Comment by isaacaflores2** [comment]
chentengming, I updated the maven dependencies. It looks like there was an issue with the junit dependencies I was using. I made sure to only use junit5. However if that does not work, you can try to add the following dependency under the maven-surefire-plugin in your pom.xml file: 
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-surefire-provider</artifactId>
    <version>${junit.platform.version}</version>
</dependency>
